<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FFDecsaSharp.Cli</AssemblyName>
    <RootNamespace>FFDecsaSharp.Cli</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <StripSymbols>true</StripSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    <IlcTrimMetadata>true</IlcTrimMetadata>
    <TrimMode>full</TrimMode>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-musl-arm64'">
    <ObjCopyName>aarch64-linux-gnu-objcopy</ObjCopyName>
  </PropertyGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-musl-x64' Or '$(RuntimeIdentifier)' == 'linux-musl-arm64'">
    <DirectPInvoke Include="libc" />
  </ItemGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-musl-x64' Or '$(RuntimeIdentifier)' == 'linux-musl-arm64'">
    <StaticExecutable>true</StaticExecutable>
    <StaticOpenSslLinking>true</StaticOpenSslLinking>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FFDecsaSharp\FFDecsaSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FFDecsaSharp.Tests" />
  </ItemGroup>

</Project>
